CREATE DATABASE ecommerce2 DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;

USE ecommerce2;

CREATE TABLE utilisateur (
  code        VARCHAR(255),
  nom         VARCHAR(255),
  prenom      VARCHAR(255),
  email       VARCHAR(255),
  mdp         VARCHAR(255),
  telephone   VARCHAR(255),
  CONSTRAINT user_pk PRIMARY KEY (code)
);

INSERT INTO utilisateur VALUES ('root', NULL, NULL, NULL, 'root', NULL);

CREATE TABLE livre (
  numero           VARCHAR(255),
  titre            VARCHAR(255),
  auteur           VARCHAR(255),
  description      TEXT,
  date_publication DATE,
  nbr_pages        INT,
  editeur          VARCHAR(255),
  edition          VARCHAR(255),
  isbn10           VARCHAR(255),
  isbn13           VARCHAR(255),
  prix             DECIMAL(10,2),
  categorie        VARCHAR(255),
  label            VARCHAR(255),
  chemin_img       VARCHAR(255),
  quantite         INT,
  CONSTRAINT numero_pk PRIMARY KEY (numero)
);

-- Policier
INSERT INTO livre (numero, titre, auteur, description, date_publication, nbr_pages, editeur, edition, isbn10, isbn13, prix, categorie, label, chemin_img, quantite)
VALUES
  ('401', "Le Mois des morts", "chrystine brouillet", "La mère de Lucien Jutras est décédée au début de la pandémie de COVID-19 et, depuis, l’adolescent se cherche. À quoi bon terminer son secondaire quand les cours sont en présentiel un jour sur deux ? Quand on sait qu’on peut mourir demain ? Sa relation avec son père, un riche entrepreneur de Québec avec lequel il ne se trouve rien en commun, se détériore de plus en plus. Tombé follement amoureux de Jacob, Lucien se sent renaître, mais cet amour déplaît infiniment au très réactionnaire. Marc-Aurèle Jutras. D’autant plus qu’il songe à se lancer en politique et qu’il n’a pas l’intention de laisser quiconque ternir sa réputation. Autour du conflit père-fils se tisse une toile complexe et étouffante, où les alliés de l’un deviennent des menaces pour l’autre.. Dans cette vingt et unième enquête de Maud Graham, Chrystine Brouillet brosse un vaste portrait social, aux très sombres nuances, dans lequel la cupidité et la soif de vengeance côtoient l’entraide et le désir de rédemption..", '2022-01-15', 320, 'Éditions Imaginaire', 'Première édition', '1234567890', '9781234567890', 29.99, 'Policier', "", "images/livres/policier/401.jpg", 43),
  ('402', "L'Étoile du désert", 'michael connelly', "Bosch et Ballard ensemble pour que justice soit faite . Après avoir quitté Le LAPD rongé par la misogynie, Le défaitisme et la bureaucratie, Renée Ballard revient prendre La direction de L'unité des Affaires non résolues récemment reformée. Elle y recrute des stars de la police et demande à Harry Bosch, maintenant à la retraite, de l'aider à résoudre l'affaire de deux jeunes femmes tuées de la même façon à dix ans d'intervalle.. Bosch ne saurait refuser : avec toutes les ressources du LAPD, peut-être pourra-t-il en profiter pour arrêter le psychopathe qui a abattu toute une famille dans le désert de Mojave et n'a jamais été retrouvé.. S'il respecte Ballard, Bosch supporte mal son autorité et cela risque de nuire à leur travail. Et les tueurs, eux, n'entendent pas se laisser prendre après toutes ces années d'impunité.. D'autant que pour Ballard, et surtout pour Bosch, le temps presse....", '2022-02-20', 280, 'Librairie Universelle', 'Deuxième édition', '0987654321', '9780987654321', 19.99, 'Policier', "", "images/livres/policier/402.jpg", 32),
  ('403', "Le Mystère des îles", 'donato carrisi', "L’anthropologue judiciaire Temperance Brennan, enquête cette fois sur une série de disparitions bizarres dans les Îles Turks et Caicos, un confetti d’îles coralliennes britanniques situées au large des Bahamas. Elle s’engouffre dans un sinistre labyrinthe au sein duquel une nouvelle technologie pourrait plonger le monde dans le chaos. Appelée pour examiner les restes d’un corps frappé par la foudre, Tempe remonte la source d’un tatouage énigmatique et se retrouve bientôt impliquée dans une affaire d’une portée prodigieuse. Depuis quelques années, de jeunes hommes — des touristes — disparaissaient dans les îles Turks et Caicos. Il y a sept ans, une première victime avait été retrouvée dans un endroit insolite, les mains coupées. Les autres s’étaient évaporées sans laisser de trace. Mais récemment, de nouveaux éléments troublants sont apparus et seule Tempe est à même de les déchiffrer. Le plus stupéfiant, c’est qu’en dehors du fait que leurs corps finissent par réapparaître dans des endroits insolites, les disparus n’ont apparemment rien en commun, et rien ne semble les prédisposer à connaître un sort aussi dramatique. Faut-il voir dans ces épouvantables événements la culture de violence des groupes criminalisés à l’œuvre dans ces îles ? Tempe en doute, d’autant que des indices troublants montrent que l’affaire pourrait avoir des prolongements d’une portée planétaire. Et bientôt, elle devient elle-même une cible..", '2022-03-25', 350, 'Aventure Éditions', 'Troisième édition', '1111111111', '9781111111111', 24.99, 'Policier', "", "images/livres/policier/403.jpg", 54),
  ('404', "La Maison aux lumières", 'donato carrisi', "Un jeu maléfique qui ne se termine jamais. . Dans une vieille bâtisse isolée en Toscane, une fillette souffre de maux bien étranges... Lors de phases de transe, Eva semble habitée par le mal et obéit aux ordres d'un ami imaginaire inquiétant.. C'est en tout cas ce que rapporte sa jeune fille au pair à Pietro Gerber, illustre hypnotiseur pour enfants. Ce dernier, traumatisé par sa précédente affaire, hésite à prendre en charge cette patiente. Mais au cours de leurs séances, elle dissémine des indices sur une histoire qui ronge Gerber depuis des décennies : la disparition brutale de son ami, survenue dans son enfance.. Comment peut-elle être au courant de détails que même Gerber a enfouis en lui ? En sondant les affres de la mémoire d'Eva, Pietro Gerber va être victime d'un jeu de piste dangereux, qui l'obligera à se confronter à ses pires démons.", '2022-04-10', 300, 'Rêveurs Press', 'Quatrième édition', '2222222222', '9782222222222', 18.99, 'Policier', "", "images/livres/policier/404.jpg", 45),
  ('405', "La Fille dans les serres de l'aigle", 'karin smirnoff', "Nouvel eldorado de l'énergie verte, le Nord de la Suède, et en particulier Gasskas, attire des entreprises avides de gains et des bandes criminelles pressées de s'enrichir. C'est pour un autre motif que Lisbeth Salander y débarque : sa nièce Svala (la fille de son détestable demi-frère) vit là-haut, seule et désormais livrée à elle- même depuis que sa mère a disparu.. Vers Gasskas se dirige aussi Mikael Blomkvist, afin de célébrer le mariage de sa fille. Mais il ignore que l'homme qu'elle épouse est un édile municipal à l'ambition démesurée, aux fréquentations dangereuses et aux pratiques des plus illégales.. Quand les forces du mal se déchaînent, Blomkvist et Salander sont pris dans la tourmente, séparés mais unis comme aux premiers jours de Millenium.. En reprenant les rênes de la saga aux millions de lecteurs, Karin Smirnoff signe un thriller palpitant et d'une actualité brûlante avec en toile de fond les conflits mal assumés des pays nordiques à l'heure de la transition écologique..", '2022-05-15', 280, 'Mystère Éditeurs', 'Cinquième édition', '3333333333', '9783333333333', 34.99, 'Policier', "", "images/livres/policier/405.jpg", 87),
  ('406', "Le Transfuge : que la chasse commence", 'chris hadfield', "Le second roman de l'un des meilleurs pilotes de chasse au monde nous fait vivre l'excitation du combat aérien. ISRAËL, OCTOBRE 1973. Alors qu'éclate la guerre du Kippour, un chasseur soviétique MiG fait un atterrissage aussi spectaculaire qu'inattendu. À bord se trouve un pilote qui, cherchant à faire défection, offre à l'Occident un prix inestimable : le Foxbat, l'avion de chasse le plus rapide qui soit. Doit-on faire confiance au transfuge ? Le contrôleur de vol de la NASA et ancien pilote d'essai américain Kaz Zemeckis, témoin de toute la scène, accompagnera le Russe aux États-Unis, sur un site d'essais hautement confidentiel au Nevada, en espérant que le jeu d'espionnage, de mensonges et de secrets se déroulera comme il l'entend.", '2022-06-20', 320, 'Aventuriers Books', 'Sixième édition', '4444444444', '9784444444444', 28.99, 'Policier', "", "images/livres/policier/406.jpg", 34),
  ('407', "Points de fuite", 'martin michaud', "Un conflit entre deux familles, les Lavoie et les Lazarre, est à l’origine de cette histoire campée dans le milieu de l’art. Sous le couvert du commerce de tableaux, Lazarre est aussi trafiquant et faussaire, et c’est Lavoie qui en devient l’exécutant pour effacer une dette de longue date.", '2022-07-05', 250, 'Chronos Éditions', 'Septième édition', '5555555555', '9785555555555', 22.99, 'Policier', "", "images/livres/policier/407.jpg", 54),
  ('408', "Éclipse totale", 'jo nesbo', "Éclipse totale . À Oslo, deux jeunes femmes sont retrouvées, l'une sans cerveau, l'autre décapitée.. Soupçonné, l'exécrable Markus Roed, magnat de l'immobilier, charge son avocat d'engager un détective, le meilleur, pour le disculper.. Hole, exclu de la police, serait l'homme de la situation s'il n'était en train de se soûler méthodiquement dans un bar de Los Angeles en compagnie de Lucille, actrice vieillissante qui doit 960 000 dollars à des recouvreurs de dette mexicains. Pour sauver son amie, Harry accepte l'offre de Roed. À ce tarif.. Il a dix jours devant lui pour rentrer affronter ses démons, trouver le coupable et envoyer l'argent.", '2022-08-12', 300, 'Sphinx Press', 'Huitième édition', '6666666666', '9786666666666', 26.99, 'Policier', "", "images/livres/policier/408.jpg", 43),
  ('409', "Le Don du mensonge", 'donna leon', "Le commissaire Brunetti vient en aide à une amie d'enfance qui soupçonne son gendre d'activités criminelles. Il mène l'enquête en compagnie de la Signorina Elettra et de la commissaire Claudia Griffoni et découvre le milieu de la mafia vénitienne.", '2022-09-25', 280, 'Rêveurs Imagination', 'Neuvième édition', '7777777777', '9787777777777', 18.99, 'Policier', "", "images/livres/policier/409.jpg", 23),
  ('410', "Lux", 'maxime chattam', "Lux . Les scientifiques comme les religieux ne peuvent expliquer ce qu'elle est ni d'où elle vient.. Elle va transformer pour toujours le quotidien du monde entier, en particulier l'existence d'une mère et de sa fille.. Tout en posant la question qui nous obsède tous.... Nos vies ont-elles un sens ?. Un roman au suspense saisissant, hommage lumineux à Barjavel et à la littérature qui divertit, qui interroge.. Maxime Chattam comme vous ne l'avez jamais lu..", '2022-10-30', 320, 'Étoile Éditeurs', 'Dixième édition', '8888888888', '9788888888888', 24.99, 'Policier', "", "images/livres/policier/410.jpg", 43);


-- Science-fiction
INSERT INTO livre (numero, titre, auteur, description, date_publication, nbr_pages, editeur, edition, isbn10, isbn13, prix, categorie, label, chemin_img, quantite)
VALUES
  ('101', "Bambi", "maude royer", "Une femme, abattue d'une balle en pleine tête, dont le meurtre demeure irrésolu. Des fidèles buvant les paroles d'un chaman au charme aussi énigmatique que ses pouvoirs. Des rituels immoraux, pratiqués au nom de l'amour infini. Des enfants affectés par d'inquiétantes difformités physiques. Un jeune homme qui n'a plus d'autres choix que de croire ce qu'il voit...", '2022-01-15', 320, "ADA", 'Première édition', '1234567890', '9781234567890', 29.99, 'science-fiction', "", "images/livres/science-fiction/101.jpg", 32),
  ('102', "Alcide le bourreau", "josée marcotte", "Un bourreau à la retraite sortant de sa tanière pour venger sa petite Marie, sa princesse. Un jeunot extravagant qui croise son chemin. Un duo improbable pour retrouver le tueur. Une enquête qui fait vibrer les échos du passé… Alcide Paquet reprend son costume de bourreau découvert dans La princesse au petit pois, convaincu que la police ne l’attrapera jamais dans ses filets. Aidé malgré lui par un coéquipier d’une autre génération, ses repères tombent les uns après les autres et ses chaînes se brisent. Dans l’oeil du cyclone, il entrevoit la vie qu’on lui a toujours interdite", '2022-02-20', 280, "ADA", 'Deuxième édition', '0987654321', '9780987654321', 19.99, 'science-fiction', "", "images/livres/science-fiction/102.jpg", 43),
  ('103', "Château de Dracula", "Kim Messier", "DESTINATION : Château de Bran, Transylvanie, Roumanie.. NATURE DU VOYAGE : Jeu d’évasion immersif dans le château qui a inspiré Dracula à Bram Stoker. NOMBRE DE VOYAGEURS : 8. La carrière de cosplayeuse professionnelle de Gabrielle stagne. On lui reproche de créer du contenu plus érotique qu’original. Afin de prouver le contraire, elle décide de se rendre dans un endroit exaltant, à l’atmosphère macabre, pour prendre des photos dans de nouveaux costumes. Elle s’embarque alors dans un voyage organisé où les participants sont enfermés dans une forteresse, obligés de se lancer dans une chasse aux indices pour trouver une clé qui leur permettra d’en sortir. Rapidement, ils comprennent qu’ils sont complètement livrés à eux-mêmes et que des événements terribles se trament dans l’ombre. Les règles du jeu commencent à changer, transformant l’aventure des voyageurs en bain de sang. Leurs heures sont comptées… Découvrez l’univers de DATO, une agence de voyage spécialisée en tourisme morbide. L’horreur et le suspense vous attendent dans tous les romans de cette collection. À lire dans n’importe quel ordre !.", '2022-03-25', 350, "MORTAGNE ED DE", 'Troisième édition', '1111111111', '9781111111111', 24.99, 'science-fiction', "", "images/livres/science-fiction/103.jpg", 12),
  ('104', "Le Hobbit", "J.R.R Tolkien", "Le Hobbit . Chef d'oeuvre du maitre de la fantasy et roman fondateur de l'univers de J. R. R. Tolkien. Le Hobbit a été publié ln 1937. Vendu à des milliers d'exemplaires de par le monde. Il a été adapté au cinéma par Peter Jackson..", '2022-04-10', 300, "POCKET", 'Quatrième édition', '2222222222', '9782222222222', 18.99, 'science-fiction', "", "images/livres/science-fiction/104.jpg", 87),
  ('105', "Le Silmarillion", "john ronald reuel tolkien", "J.R.R. Tolkien le Silmarillion . Composé de récits allant des Jours anciens de la terre du milieu à la fin de la guerre de l'anneau, en passant par le second âge et la montée en puissance de Sauron, le Silmarillion est au coeur de l'univers imaginé par J.R.R. Tolkien..", '2022-05-15', 280, "POCKET", 'Cinquième édition', '3333333333', '9783333333333', 34.99, 'science-fiction', "", "images/livres/science-fiction/105.jpg", 21),
  ('106', "Éclats miroitants", "alix e harrow", "Zinnia combat le chaos qui règne dans le monde des histoires afin de sauver la méchante reine sans nom. Une réécriture féministe du conte Blanche-Neige et les sept nains.", '2022-06-20', 320, "HACHETTE", 'Sixième édition', '4444444444', '9784444444444', 28.99, 'science-fiction', "", "images/livres/science-fiction/106.jpg", 37),
  ('107', "L'Enlèvement de Circé", "liv stone", "Décédée, Circé se retrouve face à Hermès, chargé de la guider jusqu'au royaume d'Hadès et de Perséphone. Commence alors un voyage sur le chemin des Enfers, avec le dieu pour seul allié. Cette proximité ne fait que renforcer les sentiments que chacun s'efforce de garder secrets, dans un royaume où la loi interdit toute relation entre les vivants et les morts.", '2022-07-05', 250, "HACHETTE", 'Septième édition', '5555555555', '9785555555555', 22.99, 'science-fiction', "", "images/livres/science-fiction/107.jpg", 72),
  ('108', "L'Affaire Lafon", "anne robillard", "Même si Maynard Bennett ne veut plus accepter de mandats insolites, ses associés réussissent à le persuader de se pencher sur un nouveau cas qui, une fois toutes les explications rationnelles éliminées, pourrait s’avérer fort inquiétant. En effet, Adrien Lafon, un jeune entrepreneur français, implore Bennett de venir inspecter son musée à Paris, où une grande statue égyptienne se retourne par elle-même sur son socle, toutes les nuits, à minuit. Comme le musée est sur le point d’ouvrir ses portes au public, il faut à tout prix que ce phénomène dérangeant cesse. Et voilà que Bennett et ses associés plongent tête première dans la mythologie égyptienne, non sans mettre leur vie en péril…", '2022-08-12', 300, "WELLAN", 'Huitième édition', '6666666666', '9786666666666', 26.99, 'science-fiction', "", "images/livres/science-fiction/108.jpg", 32),
  ('109', "Mountains made of glass", "scarlett st clair", "All Gesela's life, her home village of Elk has been cursed. And it isn't a single curse?it is one after another, each to be broken by a villager, each with devastating consequences. When Elk's well goes dry, it is Gesela's turn to save her town by killing the toad that lives at the bottom. Except…the toad is not a toad at all. He is an Elven prince under a curse of his own, and upon his death, his brothers come for Gesela, seeking retribution.", '2022-09-25', 280, "BLOOM BOOKS", 'Neuvième édition', '7777777777', '9787777777777', 18.99, 'science-fiction', "", "images/livres/science-fiction/109.jpg", 43),
  ('110', "Le Chant de Pasiphaé", "liv stone", "Projetée en pleine guerre de Troie, Pasiphaé n'a d'autre choix que de faire confiance à Phobos, son unique allié. Si elle veut retourner dans le présent, elle doit retrouver le Palladion, une relique appartenant à la déesse Athéna. Mais la quête s'annonce périlleuse. Un nouveau cycle de la saga Witch and God.", '2022-10-30', 320, "HACHETTE", 'Dixième édition', '8888888888', '9788888888888', 24.99, 'science-fiction', "", "images/livres/science-fiction/110.jpg", 54);

-- Poésie
INSERT INTO livre (numero, titre, auteur, description, date_publication, nbr_pages, editeur, edition, isbn10, isbn13, prix, categorie, label, chemin_img, quantite)
VALUES
  ('201', "Le Marché aux fleurs coupées", "sarah-louise pelletier-morin", "Les fleurs possèdent cette qualité exceptionnelle d’être adéquates partout, en toutes circonstances et dans tous les décors, et cette aisance à habiter les lieux les distingue de toutes les autres formes de vie. Elles sont si répandues que la plupart passent inaperçues, ce à quoi veut remédier Le marché aux fleurs coupées, en les rendant visible une à une.. Au détour d’un cheminement délicat et immatériel, Sarah-Louise Pelletier-Morin part à la recherche de l’essence de la fleur et confectionne un herbier poétiquement précis aux facettes multiples, tant intimes, biologiques, économiques, historiques que spirituelles. Déconstruisant la métaphore traditionnelle qui associe fleur et femme, elle fait le pari d’une façon autre d’être au monde, esquisse une poésie de soi et de la finitude du vivant. Entre l’humus de nos racines et l’haleine de vie qui nous porte, ce livre impose une écriture qui s’élève dans l’affirmation de sa force fragile..", '2022-01-15', 320, "LA PEUPLADE", 'Première édition', '1234567890', '9781234567890', 29.99, 'Poésie', "", "images/livres/poesie/201.jpg", 32),
  ('202', "Mon cœur accroché sur vos murs en carton", "mylène mackay | geneviève boivin-roussy", "Dans ce récit minimaliste, Mylène Mackay explore les déceptions amoureuses en révélant une sensibilité à fleur de peau, une rare verve, non sans quelques pointes d'humour. Sa langue saisissante est le fruit d’un esprit inventif regorgeant d'ingéniosité. S’imbriquent viscéralement au texte les audacieuses illustrations de Geneviève Boivin-Roussy.", '2022-01-15', 320, "SOMME TOUTE", 'Première édition', '1234567890', '9781234567890', 29.99, 'Poésie', "", "images/livres/poesie/202.jpg", 12),
  ('203', "Chambres fortes", "collectif", "En 1929, Virginia Woolf publiait Une chambre à soi, un livre hybride, primordial, entre essai, autobiographie et roman, dans lequel elle défend l’idée que pour écrire, une femme a besoin d’indépendance financière et d’une pièce bien à elle. Elle appelle les femmes à prendre en main leur vie. De cet espoir d’un avenir meilleur pour les femmes qui écrivent, que reste-t-il près de cent ans plus tard ? Comment se conjuguent maternité (ou la non-maternité) et création ? Et on fait comment pour écrire, quand on n’a pas le privilège d’avoir ce fameux lieu à soi, où rêver, penser et écrire ? On se réfugie où pour créer nos fictions, nos poèmes ? Ils ressemblent à quoi, ces lieux à nous ?", '2022-01-15', 320, "HAMAC", 'Première édition', '1234567890', '9781234567890', 29.99, 'Poésie', "", "images/livres/poesie/203.jpg", 69),
  ('204', "Choses dites et défaites", "nancy huston", "« J'ai mis du rouge à lèvres sensass sur mes blessures pour qu'elles baisent les tiennes » . Lorsque Nancy Huston rencontre cet auteur américain, le coup de foudre est immédiat. Mais l'une comme l'autre ne sont pas dupes : dès le début, cette passion court à sa perte.. Entre coups bas et pieux mensonges, une valse perverse s'installe, où l'amour et l'ego se frottent et s'affrontent.. Dans ce recueil de poèmes inédits, Nancy Huston s'amuse avec ces fragments d'un désastre amoureux..", '2022-01-15', 320, "ICONOCLASTE", 'Première édition', '1234567890', '9781234567890', 29.99, 'Poésie', "", "images/livres/poesie/204.jpg", 23),
  ('205', "Le Temps est une mère", "ocean vuong", "Recueil de poèmes à travers lesquels l'auteur explore les conséquences du deuil de sa mère et interroge les paradoxes liés à ses origines vietnamiennes.", '2022-01-15', 320, "GALLIMARD", 'Première édition', '1234567890', '9781234567890', 29.99, 'Poésie', "", "images/livres/poesie/205.jpg", 78),
  ('206', "Noël à Hochelag", "audrey hébert", "Les calendriers de l’avent sont l’invention la plus cool de l’univers. Parce qu’elle adore Noël, Audrey Hébert a décidé d’en concocter un avec des poèmes remplis d’amour et de brosses au Baileys et, pour faire durer le temps des fêtes encore plus longtemps, il commence même le premier novembre! Les gentilles gurls dégusteront un poème à la fois, alors que les naughty gurls dévoreront le livre d’un seul coup. À ces dernières, Audrey promet qu’il n’y aura pas de morceau de charbon dans leur bas de Noël!", '2022-01-15', 320, "EDITIONS DE TA MERE", 'Première édition', '1234567890', '9781234567890', 29.99, 'Poésie', "", "images/livres/poesie/206.jpg", 23),
  ('207', "Petit éloge de l'errance", "akira mizubayashi", " Petit éloge de l'errance . « C'est cet effort d'absence volontaire, de déracinement voulu, de distanciation active par rapport à son milieu qui paraît toujours naturel, c'est donc cette manière de s'éloigner de soi-même - ne serait-ce que momentanément et provisoirement -, de se séparer du natal, du national et de ce qui, plus généralement, le fixe dans une étroitesse identitaire, c'est cela et surtout cela que j'appellerai errance. ». ", '2022-01-15', 320, "GALLIMARD", 'Première édition', '1234567890', '9781234567890', 29.99, 'Poésie', "", "images/livres/poesie/207.jpg", 62),
  ('208', "Rose", "isabelle hubert", " Après une adolescence difficile, Rose est devenue une adulte équilibrée. Mais voilà que son fils de 15 ans est assailli à son tour par les tourments de l’âge ingrat. En cherchant de l’aide auprès d’un psychologue, Rose va revivre les moments les plus sombres de sa propre histoire. On assiste alors à la naissance d’une improbable amitié entre la jeune Rose et Victor, un ado singulier. Cette relation va mener Rose entre l’obscurité d’un mal de vivre et l’espoir incandescent du jour qui se lève. La pièce brosse un tableau juste et nécessaire de la souffrance psychologique qui nous habite parfois dans cette étape cruciale de notre vie et, avec empathie, montre un chemin vers la guérison. Elle nous rappelle aussi avec tendresse les grandes émotions de l’adolescence, le sentiment de ne jamais être à sa place, les amitiés foudroyantes et les conversations qui durent toute la nuit. ", '2022-01-15', 320, "INSTANT MEME", 'Première édition', '1234567890', '9781234567890', 29.99, 'Poésie', "", "images/livres/poesie/208.jpg", 74),
  ('209', "Harmony", "whitney hanson", "In this exquisite poetry collection, Whitney Hanson, chronicles the loss of a loved one, tracing the progression of grief and healing through the lens of music. We each begin with a simple note, but as life progresses, we’re led to the next note, and the next—all of which combine to form the melody of a song and a life. As life becomes more complicated and complex, we find that loss, grief, and heartache can muffle our music, making the world go silent. But as Whitney’s poems show, all of these rests and pauses in the music are part of the composition of life, and it is only by moving through the variations that we can find the harmony and grace that come with healing.", '2022-01-15', 320, "PENGUIN PRESS", 'Première édition', '1234567890', '9781234567890', 29.99, 'Poésie', "", "images/livres/poesie/209.jpg", 56),
  ('210', "Hitchcock s'est trompé", "pierre bayard", " Hitchcock s'est trompé . Il est impossible de croire sérieusement, comme les deux héros du célèbre film d'Hitchcock Fenêtre sur cour, que leur voisin aurait tué sa femme, puis l'aurait découpée en morceaux devant les fenêtres ouvertes d'une trentaine d'appartements.. Mais leur délire d'interprétation n'a pas pour seule conséquence de conduire à accuser un innocent. Il détourne l'attention d'un autre meurtre - bien réel celui-là - qui est commis devant les spectateurs à leur insu et mérite l'ouverture d'une enquête.. ", '2022-01-15', 320, "MINUIT", 'Première édition', '1234567890', '9781234567890', 29.99, 'Poésie', "", "images/livres/poesie/210.jpg", 83);

-- Histoire
INSERT INTO livre (numero, titre, auteur, description, date_publication, nbr_pages, editeur, edition, isbn10, isbn13, prix, categorie, label, chemin_img, quantite)
VALUES
  ('301', "Les Monologues du voile", "kenza bennis", " La question du voile revient régulièrement dans l'actualité, au Québec comme ailleurs, et suscite des discussions houleuses. Pour explorer la dimension proprement québécoise du phénomène, Kenza Bennis a choisi d'aller à la rencontre de Québécoises voilées et de leur donner la parole, elles que l'on entend si peu souvent. Elle a interviewé en tout 83 femmes, parmi lesquelles on trouve aussi des Québécoises dites «de souche» ainsi que des musulmanes non voilées. Ces témoignages inédits permettront de mieux connaître les femmes qui portent le foulard et la façon dont elles sont perçues. Le but? Mieux se comprendre pour mieux vivre ensemble, rappelle l'auteure dans cet essai à la fois original, courageux et nécessaire. ", '2022-01-15', 320, "ROBERT LAFFONT", 'Première édition', '1234567890', '9781234567890', 29.99, 'Histoire', "", "images/livres/histoire/301.jpg", 25),
  ('302', "21 leçons pour le XXIe siècle", "yuval noah harari", " L'historien offre ses méditations en réponse au grandes craintes de l'humanité sur les risques de guerre nucléaire, de cataclysme écologique, de désordre technologique ou de menace terroriste. Il insiste sur la responsabilisation de chacun et la nécessité de maintenir et d'accroître les liens sociaux. ", '2022-01-15', 320, "ALBIN MICHEL", 'Première édition', '1234567890', '9781234567890', 29.99, 'Histoire', "", "images/livres/histoire/302.jpg", 12),
  ('303', "Veines ouvertes de l'Amérique latine", "eduardo galeano", " L'histoire du continent permet de suivre dans le moindre détail le mécanisme qui a conduit à une dépossession ruinant les nations d'un espace très prometteur. ", '2022-01-15', 320, "POCKET", 'Première édition', '1234567890', '9781234567890', 29.99, 'Histoire', "", "images/livres/histoire/303.jpg", 86),
  ('304', "La Seconde Guerre mondiale", "antony beevor", " La Seconde Guerre mondiale est le plus grand conflit de l'histoire par ses destructions, le nombre de ses victimes et les bouleversements provoqués dans l'ordonnancement du monde et dans le paysage mental des êtres humains.. Sur la base de documents anciens et d'archives inédites, Antony Beevor nous emmène de l'Atlantique Nord au Pacifique Sud, de la Sibérie à la Libye, de la jungle birmane à Berlin bombardé, des lambris dorés des chancelleries à Leningrad assiégé, sans rien nous épargner des horreurs de la guerre, qu'il s'agisse des Einsatzgruppen sur le front Est, des prisonniers du goulag enrôlés dans des bataillons suicide, ou des exactions sadiques perpétrées par l'armée japonaise en Chine.. ", '2022-01-15', 320, "LE LIVRE DE POCHE", 'Première édition', '1234567890', '9781234567890', 29.99, 'Histoire', "", "images/livres/histoire/304.jpg", 67),
  ('305', "Le Saboteur : l'aristocrate qui défia les nazis", "paul kix", " Le portrait de Robert de La Rochefoucauld qui, en juin 1940, alors qu'il n'a que 16 ans, se rend à Londres pour y rencontrer le général de Gaulle. Il est recruté par la branche action des services secrets anglais. Parachuté en France et multipliant les identités, il accomplit de nombreuses missions. Capturé à plusieurs reprises par les Allemands, il réussit à s'évader à chaque fois. ", '2022-01-15', 320, "POCKET", 'Première édition', '1234567890', '9781234567890', 29.99, 'Histoire', "", "images/livres/histoire/305.jpg", 83),
  ('306', "Au square Gardette", "rober racine", " En mars 1983, à Paris, le compositeur Claude Vivier est assassiné par un garçon de vingt ans qu’il a, dans un bar-café de Belleville, invité à le suivre chez lui. Dans son appartement du square Gardette où, alors, Vivier travaille à une œuvre chorale, Crois-tu en l’immortalité de l’âme, sa mort rend prophétique la partition inachevée. Rober Racine, l’ami des dernières années de Vivier, s’interroge sans conclure sur les indicibles liens entre le meurtre et la création. Il livre un pénétrant témoignage sur le parcours d’un enfant abandonné, artiste doué, créateur passionné, qu’un autre enfant, également abandonné, a rayé de la vie à coups de poignard et de nuit. ", '2022-01-15', 320, "BOREAL", 'Première édition', '1234567890', '9781234567890', 29.99, 'Histoire', "", "images/livres/histoire/306.jpg", 72),
  ('307', "Ce jour-là : Parce qu'elles étaient des femmes", "josée boileau", "", '2022-01-15', 320, "LA PRESSE", 'Première édition', '1234567890', '9781234567890', 29.99, 'Histoire', "", "images/livres/histoire/307.jpg", 64),
  ('308', "Les 50 ans d'Expo 67", "luc désilets", " Il y a eu «avant l'Expo». Puis, il y a eu «après l'Expo». Du jour au lendemain, le 27 avril 1967, nous nous sommes faits les hôtes du monde entier. Du jour au lendemain, nous existions tout à coup. Le choc fut tel que l'Expo 67 s'est taillé une place incomparable dans notre imaginaire collectif. Aucun événement n'aura jamais suscité une telle unanimité! Armés d'un singulier passeport, excités à l'idée de découvrir ce que la planète avait à offrir, nous avons envahi les îles inventées d'Expo 67 comme si nous entrions au pays des merveilles. Et nous en sommes ressortis différents, plus ouverts, assoiffés de connaissance... une fois, dix fois, vingt-cinq, cinquante fois! Passant en revue les petits et grands moments qui ont marqué la mise en oeuvre de ce fabuleux projet, le livre-souvenir Expo 67: 50 ans, 50 souvenirs marquants (et autres secrets bien gardés) ravira à coup sûr les nostalgiques de ce grand moment de notre histoire collective... et tous ceux qui ont rêvé d'y prendre part. ", '2022-01-15', 320, "SAINT JEAN", 'Première édition', '1234567890', '9781234567890', 29.99, 'Histoire', "", "images/livres/histoire/308.jpg", 31),
  ('309', "Kuei, je te salue : conversations sur le racisme", "deni ellis béchard | n kanapé fontaine", " En 2016, la poète Innu Natasha Kanapé Fontaine et le romancier québéco-américain Deni Ellis Béchard entamaient une conver­sation sans tabou sur le racisme entre Autochtones et Allochtones. Comment cohabiter si notre histoire commune est empreinte de honte, de blessures et de colère? Comment faire réaliser aux Blancs le privilège invisible de la domination historique? Comment guérir les Autochtones des stigmates du génocide culturel ? Ces questions traversent leurs échanges: Natasha raconte sa découverte des pensionnats autochtones, son obsession pour la crise d'Oka, la vie dans la communauté de Pessamit; Deni parle du racisme ordinaire de son père, de la ségrégation envers les Afro-Américains, de son identité de Québécois aux États-Unis.. Cinq ans plus tard, Deni et Natasha reprennent la plume pour poursuivre ce « rendez-vous de la parole qui s'ouvre ». Renouant avec le ton intimiste et le foisonnement intellectuel de leur premier échange, ils abordent des sujets d'une brûlante actualité : mobilisation de Black Lives Matter après la mort de George Floyd, feux de forêt en Californie, campagne présidentielle sur fond de montée de l'intolérance; soulèvement des Wet'suwet'en et blocus ferroviaires, dénonciation de la politique de la reconnaissance du gouvernement Trudeau. Puis survient l'impensable: Joyce Echaquan, une Atikamekw de 37 ans, meurt sous les injures racistes de deux infirmières de l'hôpital de Joliette. Une vague d'indignation monte.... En croisant leurs mots avec franchise, leurs lettres approfondissent le dialogue nécessaire à la réconciliation entre nos peuples. Il en résulte un livre humaniste et universel sur le rapport à l'autre et le respect de la différence.. ", '2022-01-15', 320, "ECOSOCIETE", 'Première édition', '1234567890', '9781234567890', 29.99, 'Histoire', "", "images/livres/histoire/309.jpg", 32),
  ('310', "Les Sept cités du savoi", "violet moller", " Dans cet ambitieux et enthousiasmant ouvrage, Violet Moller retrace le chemin que des manuscrits antiques qu'on croyait perdus à la chute de l'Empire romain parcoururent par-delà les continents et par-delà les siècles pour être retrouvés à la Renaissance. Elle nous embarque dans les bagages d'hommes avides de connaissances, copistes et humanistes, passeurs d'ouvrages d'astronomie, de mathématiques et de médecine, sur la piste de ces sept cités du savoir qui brillaient au coeur du Moyen Age : Alexandrie, Bagdad, Cordoue, Tolède, Salerne, Palerme, Venise.", '2022-01-15', 320, "PAYOT", 'Première édition', '1234567890', '9781234567890', 29.99, 'Histoire', "", "images/livres/histoire/310.jpg", 54);
  
CREATE TABLE commande (
  numero_commande  VARCHAR(255),
  code             VARCHAR(255),
  date_commande    DATE,
  total            DECIMAL(10,2),
  CONSTRAINT numero_commande_pk PRIMARY KEY (numero_commande),
  CONSTRAINT code_fk FOREIGN KEY (code) REFERENCES utilisateur(code)
);

CREATE TABLE commande_livres (
  numero_commande  VARCHAR(255),
  numero           VARCHAR(255),
  CONSTRAINT commande_livres_pk PRIMARY KEY (numero_commande, numero),
  FOREIGN KEY (numero_commande) REFERENCES commande(numero_commande),
  FOREIGN KEY (numero) REFERENCES livre(numero)
);
