CREATE TABLE utilisateur (
  code        VARCHAR(255),
  nom         VARCHAR(255),
  prenom      VARCHAR(255),
  email       VARCHAR(255),
  mdp         VARCHAR(255),
  telephone   VARCHAR(255),
  CONSTRAINT user_pk PRIMARY KEY (code)
);

INSERT INTO utilisateur VALUES ('root', NULL, NULL, NULL, 'root', NULL);

CREATE TABLE livre (
  numero           VARCHAR(255),
  titre            VARCHAR(255),
  auteur           VARCHAR(255),
  description      TEXT,
  date_publication DATE,
  nbr_pages        INT,
  editeur          VARCHAR(255),
  edition          VARCHAR(255),
  isbn10           VARCHAR(255),
  isbn13           VARCHAR(255),
  prix             DECIMAL(10,2),
  categorie        VARCHAR(255),
  label            VARCHAR(255),
  chemin_img       VARCHAR(255),
  quantite         INT,
  CONSTRAINT numero_pk PRIMARY KEY (numero)
);

-- Policier
INSERT INTO livre (numero, titre, auteur, date_publication, nbr_pages, editeur, edition, isbn10, isbn13, prix, categorie, label, chemin_img, quantite)
VALUES
  ('001', "Le Mois des morts", "chrystine brouillet", "La mère de Lucien Jutras est décédée au début de la pandémie de COVID-19 et, depuis, l’adolescent se cherche. À quoi bon terminer son secondaire quand les cours sont en présentiel un jour sur deux ? Quand on sait qu’on peut mourir demain ? Sa relation avec son père, un riche entrepreneur de Québec avec lequel il ne se trouve rien en commun, se détériore de plus en plus. Tombé follement amoureux de Jacob, Lucien se sent renaître, mais cet amour déplaît infiniment au très réactionnaire. Marc-Aurèle Jutras. D’autant plus qu’il songe à se lancer en politique et qu’il n’a pas l’intention de laisser quiconque ternir sa réputation. Autour du conflit père-fils se tisse une toile complexe et étouffante, où les alliés de l’un deviennent des menaces pour l’autre.. Dans cette vingt et unième enquête de Maud Graham, Chrystine Brouillet brosse un vaste portrait social, aux très sombres nuances, dans lequel la cupidité et la soif de vengeance côtoient l’entraide et le désir de rédemption..", '2022-01-15', 320, 'Éditions Imaginaire', 'Première édition', '1234567890', '9781234567890', 29.99, 'Policier', NULL, NULL, NULL),
  ('002', "L'Étoile du désert", 'michael connelly', "Bosch et Ballard ensemble pour que justice soit faite . Après avoir quitté Le LAPD rongé par la misogynie, Le défaitisme et la bureaucratie, Renée Ballard revient prendre La direction de L'unité des Affaires non résolues récemment reformée. Elle y recrute des stars de la police et demande à Harry Bosch, maintenant à la retraite, de l'aider à résoudre l'affaire de deux jeunes femmes tuées de la même façon à dix ans d'intervalle.. Bosch ne saurait refuser : avec toutes les ressources du LAPD, peut-être pourra-t-il en profiter pour arrêter le psychopathe qui a abattu toute une famille dans le désert de Mojave et n'a jamais été retrouvé.. S'il respecte Ballard, Bosch supporte mal son autorité et cela risque de nuire à leur travail. Et les tueurs, eux, n'entendent pas se laisser prendre après toutes ces années d'impunité.. D'autant que pour Ballard, et surtout pour Bosch, le temps presse....", '2022-02-20', 280, 'Librairie Universelle', 'Deuxième édition', '0987654321', '9780987654321', 19.99, 'Policier', NULL, NULL, NULL),
  ('003', "Le Mystère des îles", 'donato carrisi', "L’anthropologue judiciaire Temperance Brennan, enquête cette fois sur une série de disparitions bizarres dans les Îles Turks et Caicos, un confetti d’îles coralliennes britanniques situées au large des Bahamas. Elle s’engouffre dans un sinistre labyrinthe au sein duquel une nouvelle technologie pourrait plonger le monde dans le chaos. Appelée pour examiner les restes d’un corps frappé par la foudre, Tempe remonte la source d’un tatouage énigmatique et se retrouve bientôt impliquée dans une affaire d’une portée prodigieuse. Depuis quelques années, de jeunes hommes — des touristes — disparaissaient dans les îles Turks et Caicos. Il y a sept ans, une première victime avait été retrouvée dans un endroit insolite, les mains coupées. Les autres s’étaient évaporées sans laisser de trace. Mais récemment, de nouveaux éléments troublants sont apparus et seule Tempe est à même de les déchiffrer. Le plus stupéfiant, c’est qu’en dehors du fait que leurs corps finissent par réapparaître dans des endroits insolites, les disparus n’ont apparemment rien en commun, et rien ne semble les prédisposer à connaître un sort aussi dramatique. Faut-il voir dans ces épouvantables événements la culture de violence des groupes criminalisés à l’œuvre dans ces îles ? Tempe en doute, d’autant que des indices troublants montrent que l’affaire pourrait avoir des prolongements d’une portée planétaire. Et bientôt, elle devient elle-même une cible..", '2022-03-25', 350, 'Aventure Éditions', 'Troisième édition', '1111111111', '9781111111111', 24.99, 'Policier', NULL, NULL, NULL),
  ('004', "La Maison aux lumières", 'donato carrisi', "Un jeu maléfique qui ne se termine jamais. . Dans une vieille bâtisse isolée en Toscane, une fillette souffre de maux bien étranges... Lors de phases de transe, Eva semble habitée par le mal et obéit aux ordres d'un ami imaginaire inquiétant.. C'est en tout cas ce que rapporte sa jeune fille au pair à Pietro Gerber, illustre hypnotiseur pour enfants. Ce dernier, traumatisé par sa précédente affaire, hésite à prendre en charge cette patiente. Mais au cours de leurs séances, elle dissémine des indices sur une histoire qui ronge Gerber depuis des décennies : la disparition brutale de son ami, survenue dans son enfance.. Comment peut-elle être au courant de détails que même Gerber a enfouis en lui ? En sondant les affres de la mémoire d'Eva, Pietro Gerber va être victime d'un jeu de piste dangereux, qui l'obligera à se confronter à ses pires démons.", '2022-04-10', 300, 'Rêveurs Press', 'Quatrième édition', '2222222222', '9782222222222', 18.99, 'Policier', NULL, NULL, NULL),
  ('005', "La Fille dans les serres de l'aigle", 'karin smirnoff', "Nouvel eldorado de l'énergie verte, le Nord de la Suède, et en particulier Gasskas, attire des entreprises avides de gains et des bandes criminelles pressées de s'enrichir. C'est pour un autre motif que Lisbeth Salander y débarque : sa nièce Svala (la fille de son détestable demi-frère) vit là-haut, seule et désormais livrée à elle- même depuis que sa mère a disparu.. Vers Gasskas se dirige aussi Mikael Blomkvist, afin de célébrer le mariage de sa fille. Mais il ignore que l'homme qu'elle épouse est un édile municipal à l'ambition démesurée, aux fréquentations dangereuses et aux pratiques des plus illégales.. Quand les forces du mal se déchaînent, Blomkvist et Salander sont pris dans la tourmente, séparés mais unis comme aux premiers jours de Millenium.. En reprenant les rênes de la saga aux millions de lecteurs, Karin Smirnoff signe un thriller palpitant et d'une actualité brûlante avec en toile de fond les conflits mal assumés des pays nordiques à l'heure de la transition écologique..", '2022-05-15', 280, 'Mystère Éditeurs', 'Cinquième édition', '3333333333', '9783333333333', 34.99, 'Policier', NULL, NULL, NULL),
  ('006', "Le Transfuge : que la chasse commence", 'chris hadfield', "Le second roman de l'un des meilleurs pilotes de chasse au monde nous fait vivre l'excitation du combat aérien. ISRAËL, OCTOBRE 1973. Alors qu'éclate la guerre du Kippour, un chasseur soviétique MiG fait un atterrissage aussi spectaculaire qu'inattendu. À bord se trouve un pilote qui, cherchant à faire défection, offre à l'Occident un prix inestimable : le Foxbat, l'avion de chasse le plus rapide qui soit. Doit-on faire confiance au transfuge ? Le contrôleur de vol de la NASA et ancien pilote d'essai américain Kaz Zemeckis, témoin de toute la scène, accompagnera le Russe aux États-Unis, sur un site d'essais hautement confidentiel au Nevada, en espérant que le jeu d'espionnage, de mensonges et de secrets se déroulera comme il l'entend.", '2022-06-20', 320, 'Aventuriers Books', 'Sixième édition', '4444444444', '9784444444444', 28.99, 'Policier', NULL, NULL, NULL),
  ('007', "Points de fuite", 'martin michaud', "Un conflit entre deux familles, les Lavoie et les Lazarre, est à l’origine de cette histoire campée dans le milieu de l’art. Sous le couvert du commerce de tableaux, Lazarre est aussi trafiquant et faussaire, et c’est Lavoie qui en devient l’exécutant pour effacer une dette de longue date.", '2022-07-05', 250, 'Chronos Éditions', 'Septième édition', '5555555555', '9785555555555', 22.99, 'Policier', NULL, NULL, NULL),
  ('008', "Éclipse totale", 'jo nesbo', "Éclipse totale . À Oslo, deux jeunes femmes sont retrouvées, l'une sans cerveau, l'autre décapitée.. Soupçonné, l'exécrable Markus Roed, magnat de l'immobilier, charge son avocat d'engager un détective, le meilleur, pour le disculper.. Hole, exclu de la police, serait l'homme de la situation s'il n'était en train de se soûler méthodiquement dans un bar de Los Angeles en compagnie de Lucille, actrice vieillissante qui doit 960 000 dollars à des recouvreurs de dette mexicains. Pour sauver son amie, Harry accepte l'offre de Roed. À ce tarif.. Il a dix jours devant lui pour rentrer affronter ses démons, trouver le coupable et envoyer l'argent.", '2022-08-12', 300, 'Sphinx Press', 'Huitième édition', '6666666666', '9786666666666', 26.99, 'Policier', NULL, NULL, NULL),
  ('009', "Le Don du mensonge", 'donna leon', "Le commissaire Brunetti vient en aide à une amie d'enfance qui soupçonne son gendre d'activités criminelles. Il mène l'enquête en compagnie de la Signorina Elettra et de la commissaire Claudia Griffoni et découvre le milieu de la mafia vénitienne.", '2022-09-25', 280, 'Rêveurs Imagination', 'Neuvième édition', '7777777777', '9787777777777', 18.99, 'Policier', NULL, NULL, NULL),
  ('010', "Lux", 'maxime chattam', "Lux . Les scientifiques comme les religieux ne peuvent expliquer ce qu'elle est ni d'où elle vient.. Elle va transformer pour toujours le quotidien du monde entier, en particulier l'existence d'une mère et de sa fille.. Tout en posant la question qui nous obsède tous.... Nos vies ont-elles un sens ?. Un roman au suspense saisissant, hommage lumineux à Barjavel et à la littérature qui divertit, qui interroge.. Maxime Chattam comme vous ne l'avez jamais lu..", '2022-10-30', 320, 'Étoile Éditeurs', 'Dixième édition', '8888888888', '9788888888888', 24.99, 'Policier', NULL, NULL, NULL);


-- Science-fiction
INSERT INTO livre (numero, titre, auteur, description, date_publication, nbr_pages, editeur, edition, isbn10, isbn13, prix, categorie, label, chemin_img, quantite)
VALUES
  ('101', "Bambi", "maude royer", "Une femme, abattue d'une balle en pleine tête, dont le meurtre demeure irrésolu. Des fidèles buvant les paroles d'un chaman au charme aussi énigmatique que ses pouvoirs. Des rituels immoraux, pratiqués au nom de l'amour infini. Des enfants affectés par d'inquiétantes difformités physiques. Un jeune homme qui n'a plus d'autres choix que de croire ce qu'il voit...", '2022-01-15', 320, "ADA", 'Première édition', '1234567890', '9781234567890', 29.99, 'science-fiction', NULL, NULL, NULL),
  ('102', "Alcide le bourreau", "josée marcotte", "Un bourreau à la retraite sortant de sa tanière pour venger sa petite Marie, sa princesse. Un jeunot extravagant qui croise son chemin. Un duo improbable pour retrouver le tueur. Une enquête qui fait vibrer les échos du passé… Alcide Paquet reprend son costume de bourreau découvert dans La princesse au petit pois, convaincu que la police ne l’attrapera jamais dans ses filets. Aidé malgré lui par un coéquipier d’une autre génération, ses repères tombent les uns après les autres et ses chaînes se brisent. Dans l’oeil du cyclone, il entrevoit la vie qu’on lui a toujours interdite", '2022-02-20', 280, "ADA", 'Deuxième édition', '0987654321', '9780987654321', 19.99, 'science-fiction', NULL, NULL, NULL),
  ('103', "Château de Dracula", "Kim Messier", "DESTINATION : Château de Bran, Transylvanie, Roumanie.. NATURE DU VOYAGE : Jeu d’évasion immersif dans le château qui a inspiré Dracula à Bram Stoker. NOMBRE DE VOYAGEURS : 8. La carrière de cosplayeuse professionnelle de Gabrielle stagne. On lui reproche de créer du contenu plus érotique qu’original. Afin de prouver le contraire, elle décide de se rendre dans un endroit exaltant, à l’atmosphère macabre, pour prendre des photos dans de nouveaux costumes. Elle s’embarque alors dans un voyage organisé où les participants sont enfermés dans une forteresse, obligés de se lancer dans une chasse aux indices pour trouver une clé qui leur permettra d’en sortir. Rapidement, ils comprennent qu’ils sont complètement livrés à eux-mêmes et que des événements terribles se trament dans l’ombre. Les règles du jeu commencent à changer, transformant l’aventure des voyageurs en bain de sang. Leurs heures sont comptées… Découvrez l’univers de DATO, une agence de voyage spécialisée en tourisme morbide. L’horreur et le suspense vous attendent dans tous les romans de cette collection. À lire dans n’importe quel ordre !.", '2022-03-25', 350, "MORTAGNE ED DE", 'Troisième édition', '1111111111', '9781111111111', 24.99, 'science-fiction', NULL, NULL, NULL),
  ('104', "Le Hobbit", "J.R.R Tolkien", "Le Hobbit . Chef d'oeuvre du maitre de la fantasy et roman fondateur de l'univers de J. R. R. Tolkien. Le Hobbit a été publié ln 1937. Vendu à des milliers d'exemplaires de par le monde. Il a été adapté au cinéma par Peter Jackson..", '2022-04-10', 300, "POCKET", 'Quatrième édition', '2222222222', '9782222222222', 18.99, 'science-fiction', NULL, NULL, NULL),
  ('105', "Le Silmarillion", "john ronald reuel tolkien", "J.R.R. Tolkien le Silmarillion . Composé de récits allant des Jours anciens de la terre du milieu à la fin de la guerre de l'anneau, en passant par le second âge et la montée en puissance de Sauron, le Silmarillion est au coeur de l'univers imaginé par J.R.R. Tolkien..", '2022-05-15', 280, "POCKET", 'Cinquième édition', '3333333333', '9783333333333', 34.99, 'science-fiction', NULL, NULL, NULL),
  ('106', "Éclats miroitants", "alix e harrow", "Zinnia combat le chaos qui règne dans le monde des histoires afin de sauver la méchante reine sans nom. Une réécriture féministe du conte Blanche-Neige et les sept nains.", '2022-06-20', 320, "HACHETTE", 'Sixième édition', '4444444444', '9784444444444', 28.99, 'science-fiction', NULL, NULL, NULL),
  ('107', "L'Enlèvement de Circé", "liv stone", "Décédée, Circé se retrouve face à Hermès, chargé de la guider jusqu'au royaume d'Hadès et de Perséphone. Commence alors un voyage sur le chemin des Enfers, avec le dieu pour seul allié. Cette proximité ne fait que renforcer les sentiments que chacun s'efforce de garder secrets, dans un royaume où la loi interdit toute relation entre les vivants et les morts.", '2022-07-05', 250, "HACHETTE", 'Septième édition', '5555555555', '9785555555555', 22.99, 'science-fiction', NULL, NULL, NULL),
  ('108', "L'Affaire Lafon", "anne robillard", "Même si Maynard Bennett ne veut plus accepter de mandats insolites, ses associés réussissent à le persuader de se pencher sur un nouveau cas qui, une fois toutes les explications rationnelles éliminées, pourrait s’avérer fort inquiétant. En effet, Adrien Lafon, un jeune entrepreneur français, implore Bennett de venir inspecter son musée à Paris, où une grande statue égyptienne se retourne par elle-même sur son socle, toutes les nuits, à minuit. Comme le musée est sur le point d’ouvrir ses portes au public, il faut à tout prix que ce phénomène dérangeant cesse. Et voilà que Bennett et ses associés plongent tête première dans la mythologie égyptienne, non sans mettre leur vie en péril…", '2022-08-12', 300, "WELLAN", 'Huitième édition', '6666666666', '9786666666666', 26.99, 'science-fiction', NULL, NULL, NULL),
  ('109', "Mountains made of glass", "scarlett st clair", "All Gesela's life, her home village of Elk has been cursed. And it isn't a single curse?it is one after another, each to be broken by a villager, each with devastating consequences. When Elk's well goes dry, it is Gesela's turn to save her town by killing the toad that lives at the bottom. Except…the toad is not a toad at all. He is an Elven prince under a curse of his own, and upon his death, his brothers come for Gesela, seeking retribution.", '2022-09-25', 280, "BLOOM BOOKS", 'Neuvième édition', '7777777777', '9787777777777', 18.99, 'science-fiction', NULL, NULL, NULL),
  ('110', "Le Chant de Pasiphaé", "liv stone", "Projetée en pleine guerre de Troie, Pasiphaé n'a d'autre choix que de faire confiance à Phobos, son unique allié. Si elle veut retourner dans le présent, elle doit retrouver le Palladion, une relique appartenant à la déesse Athéna. Mais la quête s'annonce périlleuse. Un nouveau cycle de la saga Witch and God.", '2022-10-30', 320, "HACHETTE", 'Dixième édition', '8888888888', '9788888888888', 24.99, 'science-fiction', NULL, NULL, NULL);






CREATE TABLE commande (
  numero_commande  VARCHAR(255),
  date_commande    DATE,
  total            DECIMAL(10,2),
  CONSTRAINT numero_commande_pk PRIMARY KEY (numero_commande)
);
